export default {
    background: '#FFF', 
    color: '#000000',
    topColor: '#00BF63',
    bottomColor: '#F4F4F4',
    iColor: 'black',
    bgIndex: '#00BF63',
    colorIndex: '#4C1C83',
    textColorIndex: '#00BF63',
    bgEnterIndex: '#44DB95',
    bgRegister: '#00BF63',
    bgMeioRegister: '#35C682',
    bgRegisterButtton: '#4C1C83',
    colorRegisterButton: '#00BF63',
    colorTextCadastro: '#4C1C83',
    colorNotYet: 'black',
    colorNaoPossuiCadastre: '#4C1C83',
    bgPerfil: '#E5E2E2',
    colorPerfil: 'white',
    bgRow: '#EFEEEE',
    borderPerfil: '#B5B5B5',
    colorIcones: 'black',
    colorVoltIcon: 'black', 
    bgAdd: 'gray',
    colorIcone2: 'white'
    
}