export default {
    background: '#FFF', 
    color: '#000000',
    topColor: '#00BF63',
    bottomColor: '#F4F4F4',
    iColor: 'black',
    bgIndex: '#00BF63',
    colorIndex: '#6D458B',
    textColorIndex: '#00BF63',
    bgEnterIndex: '#44DB95',
    bgRegister: '#00BF63',
    bgMeioRegister: '#35C682',
    bgRegisterButtton: '#6D458B',
    colorRegisterButton: '#00BF63',
    colorTextCadastro: '#6D458B',
    colorNotYet: 'black',
    colorNaoPossuiCadastre: '#6D458B',
    bgPerfil: '#E5E2E2',
    colorPerfil: 'white',
    bgRow: '#EFEEEE',
    borderPerfil: '#B5B5B5',
    colorIcones: 'black',
    colorVoltIcon: 'black',
    
}